ALTER TABLE play_history ADD COLUMN IF NOT EXISTS last_position INTEGER DEFAULT 0;
ALTER TABLE play_history ADD COLUMN IF NOT EXISTS completion_rate NUMERIC(5,4) DEFAULT 0;
ALTER TABLE play_history ADD COLUMN IF NOT EXISTS is_completed BOOLEAN DEFAULT FALSE;